name: Build APK Real-Time
on:
  repository_dispatch:
    types: [build_apk]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build APK
        run: |
          npm install -g cordova
          cordova create build_folder com.arzz.official "${{ github.event.client_payload.app_name }}"
          cd build_folder
          cordova platform add android
          echo "<html><head><script>window.location.href='${{ github.event.client_payload.web_url }}';</script></head></html>" > www/index.html
          cordova build android --release -- --keystore=../my-release-key.jks --storePassword=${{ secrets.KEYSTORE_PASSWORD }} --alias=my-alias --password=${{ secrets.KEYSTORE_PASSWORD }}

      - name: Send to Telegram
        run: |
          APK_PATH=$(find build_folder/platforms/android/app/build/outputs/apk/release -name "*.apk" | head -n 1)
          curl -F document=@"$APK_PATH" "https://api.telegram.org/bot${{ secrets.TELE_TOKEN }}/sendDocument?chat_id=${{ github.event.client_payload.chat_id }}&caption=✅ APK Berhasil Dibuat (Secure HTTPS)"
